# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Áine O'Toole
email: aine.otoole@ed.ac.uk
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "aineotoole.co.uk" # the base hostname & protocol for your site

# Logo settings
logo-image-url: images/logo.svg

# Social settings
github_username: aineniamh
twitter_username: AineToole

# Build settings
markdown: kramdown

# Layout settings
home-link-in-menu: yes

include: ['_papers','_software','_locations']
collections:
  - software
  - papers
  - locations